# Generated by Django 5.1.2 on 2025-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_logstatus_whistlepercept"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
