# Generated by Django 5.1.2 on 2025-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_log_is_favourite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videorecording",
            name="urls",
        ),
        migrations.AddField(
            model_name="event",
            name="event_folder",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="game_folder",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="git_commit",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="videorecording",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("GoPro", "GoPro"), ("PiCam", "PiCam")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="videorecording",
            name="url",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="videorecording",
            name="video_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
