# Generated by Django 5.1.2 on 2025-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_id",
            field=models.IntegerField(unique=True),
        ),
    ]
