# Generated by Django 5.1.2 on 2025-06-24 15:53

from django.db import migrations


def load_initial_data(apps, schema_editor):
    Team = apps.get_model("common", "Team")
    if not Team.objects.exists():
        Team.objects.create(team_id="0", name="Invisibles")
        Team.objects.create(team_id="3", name="Bembelbots")
        Team.objects.create(team_id="4", name="Berlin United")
        Team.objects.create(team_id="5", name="B-Human")
        Team.objects.create(team_id="8", name="Dutch Nao Team")
        Team.objects.create(team_id="12", name="Nao Devils")
        Team.objects.create(team_id="13", name="HTWK Robots")
        Team.objects.create(team_id="17", name="RoboEireann")
        Team.objects.create(team_id="18", name="rUNSWift")
        Team.objects.create(team_id="19", name="SPQR Team")
        Team.objects.create(team_id="24", name="HULKs")
        Team.objects.create(team_id="33", name="NomadZ")
        Team.objects.create(team_id="45", name="Naova")
        Team.objects.create(team_id="50", name="R-ZWEI KICKERS")
        Team.objects.create(team_id="51", name="RedBackBots")
        Team.objects.create(team_id="54", name="WisTex United")


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_team_name_alter_team_team_id"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
