# Generated by Django 5.1.2 on 2025-06-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_add_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="new_team1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1",
                to="common.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="new_team2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2",
                to="common.team",
            ),
        ),
    ]
