# Generated by Django 5.1.2 on 2025-06-25 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_game_new_team1_game_new_team2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="team1",
        ),
        migrations.RemoveField(
            model_name="game",
            name="team2",
        ),
    ]
