# Generated by Django 5.1.2 on 2025-10-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=30)),
                ("head_number", models.IntegerField(blank=True, null=True)),
                ("body_serial", models.CharField(blank=True, max_length=20, null=True)),
                ("head_serial", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
