# Generated by Django 5.1.2 on 2025-10-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_robot_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
