# Generated by Django 5.1.2 on 2025-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0022_log_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="model",
            field=models.CharField(
                choices=[("Nao", "Nao"), ("Booster K1", "Booster K1")], max_length=30
            ),
        ),
    ]
