# Generated by Django 5.2.8 on 2025-11-12 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0024_log_robot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="body_serial",
        ),
        migrations.RemoveField(
            model_name="log",
            name="head_number",
        ),
        migrations.RemoveField(
            model_name="log",
            name="head_serial",
        ),
        migrations.RemoveField(
            model_name="log",
            name="robot_version",
        ),
    ]
