# Generated by Django 5.2.8 on 2025-11-13 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_healthissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthissues',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
