# Generated by Django 5.2.8 on 2025-11-16 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0009_remove_annotation_tags_delete_annotationtag"),
        ("common", "0027_alter_healthissues_created"),
        ("image", "0006_remove_naoimage_tags_delete_naoimagetag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
