# Generated by Django 5.2.8 on 2025-11-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognition', '0008_audiodata_size_audiodata_start_pos_and_more'),
        ('common', '0028_delete_tag'),
        ('motion', '0005_accelerometerdata_size_accelerometerdata_start_pos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognition_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_mapping', to='cognition.cognitionframe')),
                ('motion_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognition_mapping', to='motion.motionframe')),
            ],
        ),
    ]
