# Generated by Django 5.2.8 on 2025-11-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='is_favourite',
        ),
    ]
