# Generated by Django 5.2.8 on 2025-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_remove_log_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatus',
            name='RobotPose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
