# Generated by Django 6.0 on 2026-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0032_experiment_experiment_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_testevent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
