# Generated by Django 6.0 on 2026-04-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_alter_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='labelstudio_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
