# Generated by Django 6.0.4 on 2026-05-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0038_alter_game_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_id",
            field=models.PositiveIntegerField(),
        ),
    ]
