# Generated by Django 6.0.3 on 2026-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_alter_team_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="bottom_video_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="top_video_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
