# Generated by Django 6.0.3 on 2026-05-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0040_log_bottom_video_path_log_top_video_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="bottom_video_path_labelstudio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="top_video_path_labelstudio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
