# Generated by Django 6.0.5 on 2026-07-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="common.event",
            ),
        ),
    ]
