# Generated by Django 6.0.5 on 2026-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_team_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("event", "name")},
        ),
    ]
