# Generated by Django 6.0.5 on 2026-07-03 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0043_alter_team_name_alter_team_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("event", "team_id", "name")},
        ),
    ]
