apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs
  annotations:
spec:
  project: default
  source:
    repoURL: 'git@github.com:BerlinUnited/Visual-Analytics.git'
    path: deployment/docs
    targetRevision: HEAD
    helm:
      releaseName: docs
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true