# Generated by Django 5.1.2 on 2025-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cognition", "0007_alter_cognitionframe_closest_motion_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiodata",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiodata",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballcandidates",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballcandidates",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballcandidatestop",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballcandidatestop",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballmodel",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballmodel",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameramatrix",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameramatrix",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameramatrixtop",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameramatrixtop",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldpercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldpercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldpercepttop",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldpercepttop",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalpercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalpercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalpercepttop",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalpercepttop",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multiballpercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multiballpercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="odometrydata",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="odometrydata",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ransaccirclepercept2018",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ransaccirclepercept2018",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ransaclinepercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ransaclinepercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robotinfo",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="robotinfo",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanlineedgelpercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanlineedgelpercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanlineedgelpercepttop",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanlineedgelpercepttop",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shortlinepercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shortlinepercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammessagedecision",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammessagedecision",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstate",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamstate",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whistlepercept",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whistlepercept",
            name="start_pos",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
