# Generated by Django 6.0.3 on 2026-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cognition", "0009_robotpose"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FrameFilter",
        ),
    ]
