# Generated by Django 6.0.3 on 2026-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cognition", "0010_delete_framefilter"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ballmodel",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="idx_repr_has_data",
            ),
        ),
    ]
