# Generated by Django 6.0.3 on 2026-06-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognition", "0011_ballmodel_idx_repr_has_data"),
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballmodel",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballmodel2",
                to="common.log",
            ),
            preserve_default=False,
        ),
    ]
