# Generated by Django 6.0.3 on 2026-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognition", "0013_audiodata_log_ballcandidates_log_and_more"),
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ballmodel",
            index=models.Index(fields=["log", "id"], name="ballmodel_log_id_idx"),
        ),
    ]
