# Generated by Django 6.0.3 on 2026-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognition", "0014_ballmodel_ballmodel_log_id_idx"),
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ballmodel",
            new_name="idx_data",
            old_name="idx_repr_has_data",
        ),
        migrations.AddIndex(
            model_name="audiodata",
            index=models.Index(fields=["log", "id"], name="audiodata_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="audiodata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="audiodata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="ballcandidates",
            index=models.Index(fields=["log", "id"], name="ballcandidates_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="ballcandidates",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="ballcandidates_data",
            ),
        ),
        migrations.AddIndex(
            model_name="ballcandidatestop",
            index=models.Index(
                fields=["log", "id"], name="ballcandidatestop_log_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ballcandidatestop",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="ballcandidatestop_data",
            ),
        ),
        migrations.AddIndex(
            model_name="cameramatrix",
            index=models.Index(fields=["log", "id"], name="cameramatrix_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="cameramatrix",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="cameramatrix_data",
            ),
        ),
        migrations.AddIndex(
            model_name="cameramatrixtop",
            index=models.Index(fields=["log", "id"], name="cameramatrixtop_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="cameramatrixtop",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="cameramatrixtop_data",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpercept",
            index=models.Index(fields=["log", "id"], name="fieldpercept_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="fieldpercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="fieldpercept_data",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpercepttop",
            index=models.Index(fields=["log", "id"], name="fieldpercepttop_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="fieldpercepttop",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="fieldpercepttop_data",
            ),
        ),
        migrations.AddIndex(
            model_name="goalpercept",
            index=models.Index(fields=["log", "id"], name="goalpercept_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="goalpercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="goalpercept_data",
            ),
        ),
        migrations.AddIndex(
            model_name="goalpercepttop",
            index=models.Index(fields=["log", "id"], name="goalpercepttop_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="goalpercepttop",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="goalpercepttop_data",
            ),
        ),
        migrations.AddIndex(
            model_name="multiballpercept",
            index=models.Index(
                fields=["log", "id"], name="multiballpercept_log_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multiballpercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="multiballpercept_data",
            ),
        ),
        migrations.AddIndex(
            model_name="odometrydata",
            index=models.Index(fields=["log", "id"], name="odometrydata_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="odometrydata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="odometrydata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="ransaccirclepercept2018",
            index=models.Index(
                fields=["log", "id"], name="ransaccirclepercept2018_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ransaccirclepercept2018",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="ransaccirclepercept2018_data",
            ),
        ),
        migrations.AddIndex(
            model_name="ransaclinepercept",
            index=models.Index(fields=["log", "id"], name="ransaclinepercept_idx"),
        ),
        migrations.AddIndex(
            model_name="ransaclinepercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="ransaclinepercept_data",
            ),
        ),
        migrations.AddIndex(
            model_name="robotinfo",
            index=models.Index(fields=["log", "id"], name="robotinfo_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="robotinfo",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="robotinfo_data",
            ),
        ),
        migrations.AddIndex(
            model_name="robotpose",
            index=models.Index(fields=["log", "id"], name="robotpose_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="robotpose",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="robotpose_data",
            ),
        ),
        migrations.AddIndex(
            model_name="scanlineedgelpercept",
            index=models.Index(fields=["log", "id"], name="scanlineedgelpercept_idx"),
        ),
        migrations.AddIndex(
            model_name="scanlineedgelpercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="scanlineedgelpercept_data",
            ),
        ),
        migrations.AddIndex(
            model_name="scanlineedgelpercepttop",
            index=models.Index(
                fields=["log", "id"], name="scanlineedgelpercepttop_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanlineedgelpercepttop",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="scanlineedgelpercepttop_data",
            ),
        ),
        migrations.AddIndex(
            model_name="shortlinepercept",
            index=models.Index(
                fields=["log", "id"], name="shortlinepercept_log_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shortlinepercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="shortlinepercept_data",
            ),
        ),
        migrations.AddIndex(
            model_name="teammessagedecision",
            index=models.Index(
                fields=["log", "id"], name="teammessagedecision_log_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammessagedecision",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="teammessagedecision_data",
            ),
        ),
        migrations.AddIndex(
            model_name="teamstate",
            index=models.Index(fields=["log", "id"], name="teamstate_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="teamstate",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="teamstate_data",
            ),
        ),
        migrations.AddIndex(
            model_name="whistlepercept",
            index=models.Index(fields=["log", "id"], name="whistlepercept_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="whistlepercept",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="whistlepercept_data",
            ),
        ),
    ]
