# Generated by Django 6.0.3 on 2026-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cognition", "0015_rename_idx_repr_has_data_idx_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiodata",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ballcandidates",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ballcandidatestop",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ballmodel",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameramatrix",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cameramatrixtop",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldpercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldpercepttop",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goalpercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goalpercepttop",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multiballpercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="odometrydata",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ransaccirclepercept2018",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ransaclinepercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="robotinfo",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="robotpose",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanlineedgelpercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanlineedgelpercepttop",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shortlinepercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teammessagedecision",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teamstate",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="whistlepercept",
            name="start_pos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
