# Generated by Django 6.0.5 on 2026-06-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cognition", "0016_alter_audiodata_start_pos_and_more"),
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogFirstFrame",
            fields=[
                (
                    "log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="log_first_frame",
                        serialize=False,
                        to="common.log",
                    ),
                ),
                (
                    "first_ready_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_ready_frame",
                        to="cognition.cognitionframe",
                    ),
                ),
                (
                    "first_set_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_set_frame",
                        to="cognition.cognitionframe",
                    ),
                ),
                (
                    "first_standby_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_standby_frame",
                        to="cognition.cognitionframe",
                    ),
                ),
            ],
        ),
    ]
