apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-fileserver
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/renew-before: "1h"
spec:
  secretName: tls-cert-fileserver
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: logs.berlin-united.com
  dnsNames:
  - logs.berlin-united.com
  - datasets.berlin-united.com
  - models.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-fileserver
    kind: Issuer