apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-models
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-models
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: models.berlin-united.com
  dnsNames:
  - models.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-models
    kind: Issuer