apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf2
data:
  nginx.conf2: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  1024;
    }

    http {
      server {
        listen *:80;
        server_name datasets.berlin-united.com;

        keepalive_timeout 65;
        keepalive_requests 100;

        root /mnt/datasets;
        autoindex on;

        location / {

          if ($request_method = 'OPTIONS') {
              add_header 'Access-Control-Allow-Origin' '*';
              add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
              add_header 'Access-Control-Max-Age' 1728000;
              add_header 'Content-Type' 'text/plain; charset=utf-8';
              add_header 'Content-Length' 0;
              return 204;
          }
        }
      }
    }