apiVersion: v2
name: monitoring
description: VAT Monitoring Helm Chart
type: application
version: 0.1.0
appVersion: "0.0.10"

dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 8.13.1
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts/prometheus
    version: 27.32.0
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.37.0
  - name: vector
    repository: https://helm.vector.dev
    version: 0.45.0