# Generated by Django 6.0.3 on 2026-06-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
        ("motion", "0006_imudata_motion_imud_frame_i_491be9_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="accelerometerdata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accelerometerdata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buttondata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buttondata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fsrdata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fsrdata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imudata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imudata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensorjointdata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensorjointdata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
    ]
