# Generated by Django 6.0.3 on 2026-06-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
        ("motion", "0007_accelerometerdata_log_buttondata_log_fsrdata_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gyrometerdata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gyrometerdata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inertialsensordata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inertialsensordata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motionstatus",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motionstatus2",
                to="common.log",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="motorjointdata",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motorjointdata2",
                to="common.log",
            ),
            preserve_default=False,
        ),
    ]
