# Generated by Django 6.0.3 on 2026-06-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
        ("motion", "0008_gyrometerdata_log_inertialsensordata_log_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="imudata",
            name="motion_imud_frame_i_491be9_idx",
        ),
        migrations.AddIndex(
            model_name="buttondata",
            index=models.Index(fields=["log", "id"], name="buttondata_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="buttondata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="buttondata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="fsrdata",
            index=models.Index(fields=["log", "id"], name="fsrdata_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="fsrdata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="fsrdata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="imudata",
            index=models.Index(fields=["log", "id"], name="imudata_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="imudata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="imudata_data",
            ),
        ),
    ]
