# Generated by Django 6.0.3 on 2026-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0041_log_bottom_video_path_labelstudio_and_more"),
        ("motion", "0009_remove_imudata_motion_imud_frame_i_491be9_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accelerometerdata",
            index=models.Index(fields=["log", "id"], name="accelerometerdata_idx"),
        ),
        migrations.AddIndex(
            model_name="accelerometerdata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="accelerometerdata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="gyrometerdata",
            index=models.Index(fields=["log", "id"], name="gyrometerdata_idx"),
        ),
        migrations.AddIndex(
            model_name="gyrometerdata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="gyrometerdata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="inertialsensordata",
            index=models.Index(fields=["log", "id"], name="inertialsensordata_idx"),
        ),
        migrations.AddIndex(
            model_name="inertialsensordata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="inertialsensordata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="motionstatus",
            index=models.Index(fields=["log", "id"], name="motionstatus_idx"),
        ),
        migrations.AddIndex(
            model_name="motionstatus",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="motionstatus_data",
            ),
        ),
        migrations.AddIndex(
            model_name="motorjointdata",
            index=models.Index(fields=["log", "id"], name="motorjointdata_idx"),
        ),
        migrations.AddIndex(
            model_name="motorjointdata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="motorjointdata_data",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorjointdata",
            index=models.Index(fields=["log", "id"], name="sensorjointdata_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorjointdata",
            index=models.Index(
                condition=models.Q(
                    models.Q(("representation_data__isnull", True), _negated=True),
                    models.Q(("representation_data", []), _negated=True),
                    models.Q(("representation_data", {}), _negated=True),
                ),
                fields=["frame"],
                name="sensorjointdata_data",
            ),
        ),
    ]
