apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  1024;
    }

    http {
      
      server {
        listen *:80;
        server_name docs.berlin-united.com;

        keepalive_timeout 65;
        keepalive_requests 100;

        root /usr/share/nginx/html;
        index index.html;


      }

    }