# Generated by Django 5.2.8 on 2025-11-16 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0005_naoimage_tags_alter_naoimagetag_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="naoimage",
            name="tags",
        ),
        migrations.DeleteModel(
            name="NaoImageTag",
        ),
    ]
