# Generated by Django 5.2.8 on 2025-11-16 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0006_remove_naoimage_tags_delete_naoimagetag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="naoimage",
            unique_together=set(),
        ),
    ]
