# Generated by Django 5.2.8 on 2025-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_remove_naoimage_resolution_naoimage_labelstudio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoimage',
            name='validated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
