# Generated by Django 6.0.3 on 2026-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0010_naoimage_unique_frame_camera_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="naoimage",
            name="annotation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
