# Generated by Django 6.0.3 on 2026-05-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0011_naoimage_annotation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="naoimage",
            old_name="validated",
            new_name="has_annotations",
        ),
    ]
