# Generated by Django 6.0.3 on 2026-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0012_rename_validated_naoimage_has_annotations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naoimage",
            name="has_annotations",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
