# Generated by Django 6.0.3 on 2026-05-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_log_bottom_video_path_log_top_video_path"),
        ("image", "0013_alter_naoimage_has_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="naoimage",
            name="log",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="common.log",
            ),
            preserve_default=False,
        ),
    ]
