# Generated by Django 6.0.3 on 2026-05-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognition", "0010_delete_framefilter"),
        ("common", "0040_log_bottom_video_path_log_top_video_path"),
        ("image", "0014_naoimage_log"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="naoimage",
            index=models.Index(fields=["log", "id"], name="naoimage_log_id_idx"),
        ),
        migrations.AddIndex(
            model_name="naoimage",
            index=models.Index(
                fields=["log", "camera", "type"], name="naoimage_log_filter_idx"
            ),
        ),
    ]
