# Generated by Django 6.0.4 on 2026-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0002_initial"),
        ("cognition", "0010_delete_framefilter"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="behaviorframeoption",
            name="behavior_be_frame_i_36b8b1_idx",
        ),
        migrations.RenameField(
            model_name="behaviorframeoption",
            old_name="options_id",
            new_name="option",
        ),
        migrations.RenameField(
            model_name="behavioroptionstate",
            old_name="option_id",
            new_name="option",
        ),
        migrations.AlterUniqueTogether(
            name="behaviorframeoption",
            unique_together={("option", "frame", "active_state")},
        ),
        migrations.AddIndex(
            model_name="behaviorframeoption",
            index=models.Index(
                fields=["frame", "option"], name="behavior_be_frame_i_05af01_idx"
            ),
        ),
    ]
