# Generated by Django 5.1.2 on 2025-04-27 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0002_annotationclass_alter_annotation_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="image",
        ),
        migrations.DeleteModel(
            name="AnnotationClass",
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
    ]
