# Generated by Django 5.1.2 on 2025-07-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0007_annotationtag"),
        ("common", "0018_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="tags",
            field=models.ManyToManyField(
                related_name="annotations_set",
                through="annotation.AnnotationTag",
                to="common.tag",
            ),
        ),
        migrations.AlterField(
            model_name="annotationtag",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_links",
                to="annotation.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="annotationtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_links",
                to="common.tag",
            ),
        ),
    ]
