# Generated by Django 5.2.8 on 2025-11-16 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0008_annotation_tags_alter_annotationtag_annotation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="tags",
        ),
        migrations.DeleteModel(
            name="AnnotationTag",
        ),
    ]
