# Generated by Django 6.0.3 on 2026-03-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_remove_annotation_tags_delete_annotationtag'),
        ('image', '0010_naoimage_unique_frame_camera_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image.naoimage')),
            ],
        ),
    ]
