# Generated by Django 6.0.3 on 2026-04-11 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0010_validation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validation",
            name="image",
        ),
        migrations.RemoveField(
            model_name="videoannotation",
            name="frame",
        ),
        migrations.RemoveField(
            model_name="videoframe",
            name="video",
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
        migrations.DeleteModel(
            name="Validation",
        ),
        migrations.DeleteModel(
            name="VideoAnnotation",
        ),
        migrations.DeleteModel(
            name="VideoFrame",
        ),
    ]
