# Generated by Django 6.0.3 on 2026-05-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "annotation",
            "0011_remove_validation_image_remove_videoannotation_frame_and_more",
        ),
        ("cognition", "0010_delete_framefilter"),
        ("common", "0038_alter_game_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Situation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("video_start_frame", models.IntegerField(blank=True, null=True)),
                ("video_end_frame", models.IntegerField(blank=True, null=True)),
                (
                    "end_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_end",
                        to="cognition.cognitionframe",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_log",
                        to="common.log",
                    ),
                ),
                (
                    "start_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_start",
                        to="cognition.cognitionframe",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_video",
                        to="common.videorecording",
                    ),
                ),
            ],
        ),
    ]
