# Generated by Django 6.0.3 on 2026-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0012_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawGCSituation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
