# Generated by Django 6.0.3 on 2026-06-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0013_rawgcsituation"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawgcsituation",
            name="uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
