# Generated by Django 6.0.5 on 2026-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotation", "0014_rawgcsituation_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawgcsituation",
            name="audio",
            field=models.CharField(blank=True, null=True),
        ),
    ]
